package StringApp;

/**
* StringApp/UpperCaseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UpperCase.idl
* Thursday, 7 May, 2026 2:44:26 AM IST
*/

public final class UpperCaseHolder implements org.omg.CORBA.portable.Streamable
{
  public StringApp.UpperCase value = null;

  public UpperCaseHolder ()
  {
  }

  public UpperCaseHolder (StringApp.UpperCase initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringApp.UpperCaseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringApp.UpperCaseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringApp.UpperCaseHelper.type ();
  }

}
