package StringApp;


/**
* StringApp/UpperCase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UpperCase.idl
* Thursday, 7 May, 2026 2:44:26 AM IST
*/

public interface UpperCase extends UpperCaseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface UpperCase
