package StringApp;


/**
* StringApp/UpperCaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UpperCase.idl
* Thursday, 7 May, 2026 2:44:26 AM IST
*/

public interface UpperCaseOperations 
{
  String toUpperCase (String str);
} // interface UpperCaseOperations
